[theme]
base = "dark"
primaryColor = "#3fb8d8"
backgroundColor = "#0a2945"
secondaryBackgroundColor = "#0d3252"
textColor = "#e5ecf6"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
